"""empty message

Revision ID: 21443fca61e9
Revises: d6a50b033dfc
Create Date: 2017-03-19 10:19:41.741627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21443fca61e9'
down_revision = 'd6a50b033dfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
